import type { AppProps } from 'next/app'
import Head from 'next/head';
import '../styles/global.css';

export default function App ({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Data Visualization App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta property="og:title" content="Data Visualization App" />
        <meta property="og:description" content="This is a app for Data Visualization." />
        <meta property="og:image" content="" />
        <meta property="og:url" content="" />
        <meta name="author" content="Martin Ivanko" />

      </Head>
      <Component {...pageProps} />
    </>
  )
}
